import {
	Coordinates,
	DiscordStatus,
	StatusConfig,
	WeatherDescription,
} from "./model";

export const APP_CONFIG = {
	LOCATION: { latitude: 53.4, longitude: 14.5 } as Coordinates,
	TIME_ZONE: "Europe/Warsaw",
	ENDPOINTS: {
		WAKATIME: "https://services.kai.enterprises/wakatime",
		DISCORD: "https://services.kai.enterprises/discord",
		WEATHER: "https://api.open-meteo.com/v1/forecast",
	},
	SELECTORS: {
		CLOCK: "#current_time",
		WAKATIME: "#wakatime",
		LASTFM: {
			COVER: "#lastfm_cover",
			COVER_BLUR: "#lastfm_cover_blur",
			TITLE: "#lastfm_title",
			SUBTITLE: "#lastfm_subtitle",
		},
		WEATHER: {
			TEMP: "#weather_temp",
			CONDITION: "#weather_condition",
		},
		ONLINE_STATUS: "#online_status",
		STATUS_INDICATOR: "#status_indicator",
		LOADING: "#loading_reminder",
	},
	STATUS_CONFIG: {
		[DiscordStatus.Online]: {
			statusText: "online",
			textColor: "text-emerald-500",
			shadowColor: "shadow-emerald-500",
			bgColor: "bg-emerald-500",
		},
		[DiscordStatus.Dnd]: {
			statusText: "busy",
			textColor: "text-red-500",
			shadowColor: "shadow-red-500",
			bgColor: "bg-red-500",
		},
		[DiscordStatus.Offline]: {
			statusText: "offline",
			textColor: "text-blue-400",
			shadowColor: "shadow-blue-400",
			bgColor: "bg-blue-400",
		},
		[DiscordStatus.Idle]: {
			statusText: "away",
			textColor: "text-amber-500",
			shadowColor: "shadow-amber-500",
			bgColor: "bg-amber-500",
		},
	} as StatusConfig,
	WEATHER_DESCRIPTIONS: {
		0: "Clear skies",
		1: "Partly cloudy",
		2: "Cloudy",
		3: "Overcast",
		4: "Visibility reduced by smoke",
		5: "Haze",
		6: "Dust in suspension",
		7: "Dust or sand raised by wind",
		8: "Dust or sand whirls",
		9: "Dust storm or sandstorm",
		10: "Mist",
		11: "Shallow fog",
		12: "Continuous fog",
		13: "Lightning visible, no thunder heard",
		14: "Precipitation within sight, not reaching the ground",
		15: "Distant precipitation",
		16: "Precipitation near the station",
		17: "Thunderstorm, no precipitation",
		18: "Squalls",
		19: "Funnel cloud",
		20: "Drizzle, slight",
		21: "Drizzle, moderate",
		22: "Drizzle, heavy",
		23: "Drizzle and rain, slight",
		24: "Drizzle and rain, moderate",
		25: "Drizzle and rain, heavy",
		26: "Freezing drizzle",
		27: "Shower(s) of rain",
		28: "Shower(s) of snow",
		29: "Shower(s) of hail",
		30: "Slight duststorm or sandstorm",
		31: "Moderate duststorm or sandstorm",
		32: "Severe duststorm or sandstorm",
		33: "Slight blowing snow",
		34: "Moderate blowing snow",
		35: "Heavy blowing snow",
		36: "Slight drifting snow",
		37: "Moderate drifting snow",
		38: "Heavy drifting snow",
		39: "Slight or moderate snow",
		40: "Heavy snow",
		41: "Slight or moderate hail",
		42: "Heavy hail",
		43: "Slight or moderate ice pellets",
		44: "Heavy ice pellets",
		45: "Slight or moderate snow pellets",
		46: "Heavy snow pellets",
		47: "Slight or moderate snow grains",
		48: "Heavy snow grains",
		49: "Slight or moderate ice crystals",
		50: "Heavy ice crystals",
		51: "Slight or moderate snow crystals",
		52: "Heavy snow crystals",
		53: "Slight or moderate snowflakes",
		54: "Heavy snowflakes",
		55: "Slight or moderate snow grains",
		56: "Heavy snow grains",
		57: "Slight or moderate snow pellets",
		58: "Heavy snow pellets",
		59: "Slight or moderate snow crystals",
		60: "Heavy snow crystals",
		61: "Slight or moderate snowflakes",
		62: "Heavy snowflakes",
		63: "Slight or moderate snow grains",
		64: "Heavy snow grains",
		65: "Slight or moderate snow pellets",
		66: "Heavy snow pellets",
		67: "Slight or moderate snow crystals",
		68: "Heavy snow crystals",
		69: "Slight or moderate snowflakes",
		70: "Heavy snowflakes",
		71: "Slight or moderate snow grains",
		72: "Heavy snow grains",
		73: "Slight or moderate snow pellets",
		74: "Heavy snow pellets",
		75: "Slight or moderate snow crystals",
		76: "Heavy snow crystals",
		77: "Slight or moderate snowflakes",
		78: "Heavy snowflakes",
		79: "Slight or moderate snow grains",
		80: "Heavy snow grains",
		81: "Slight or moderate snow pellets",
		82: "Heavy snow pellets",
		83: "Slight or moderate snow crystals",
		84: "Heavy snow crystals",
		85: "Slight or moderate snowflakes",
		86: "Heavy snowflakes",
		87: "Slight or moderate snow grains",
		88: "Heavy snow grains",
		89: "Slight or moderate snow pellets",
		90: "Heavy snow pellets",
		91: "Slight or moderate snow crystals",
		92: "Heavy snow crystals",
		93: "Slight or moderate snowflakes",
		94: "Heavy snowflakes",
		95: "Slight or moderate snow grains",
		96: "Heavy snow grains",
		97: "Slight or moderate snow pellets",
		98: "Heavy snow pellets",
		99: "Slight or moderate snow crystals",
	} as WeatherDescription,
};
